spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url: 
     defaultZone: http://192.168.127.1:8302/eureka/
#      waitTimeInMsWhenSyncEmpty: 0